[project]
name = "uv-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.15.1",
    "requests",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
